[workspace]
resolver = "2"
members = ["core", "gui", "tools/seal-bundle"]

[workspace.package]
edition = "2021"
rust-version = "1.88"
version = "0.1.0"

[workspace.dependencies]
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = "0.4"
sha2 = "0.10.9"
hmac = "0.12.1"
aes-gcm = "0.10.3"
argon2 = "0.5"
fs4 = { version = "0.6.6", default-features = false, features = ["sync"] }
rayon = "1.10.0"
walkdir = "2"
yara-x = "0.5.0"
winreg = "0.56"
windows = { version = "0.58", features = ["Win32_Foundation", "Win32_Storage_FileSystem", "Win32_Security", "Win32_Security_Authorization"] }
