[package]
name = "powerscanner-core"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
hex.workspace = true
sha2.workspace = true
hmac.workspace = true
aes-gcm.workspace = true
argon2.workspace = true
rayon.workspace = true
walkdir.workspace = true
yara-x.workspace = true

[target.'cfg(windows)'.dependencies]
winreg.workspace = true
windows.workspace = true
